### ISSUE TITLE
php 5.6

### ISSUE THREAD

**Issue by DuR4c3ll** [Empornium/Luminance#10]
It would be _nice_ if the INSTALL.md could include the exact command to install php 5.6 and the necessary dependencies.

I have installed it but when I try and install **php-memcache php-mysqlnd** it complains see below

`Resolving Dependencies
--> Running transaction check
---> Package php-fpm.x86_64 0:5.4.16-43.el7_4.1 will be installed
--> Processing Dependency: php-common(x86-64) = 5.4.16-43.el7_4.1 for package: php-fpm-5.4.16-43.el7_4.1.x86_64
--> Running transaction check
---> Package php-common.x86_64 0:5.4.16-43.el7_4.1 will be installed
--> Processing Conflict: php56u-common-5.6.34-1.ius.centos7.x86_64 conflicts php-common < 5.6
--> Finished Dependency Resolution
Error: php56u-common conflicts with php-common-5.4.16-43.el7_4.1.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest`

Any help would be appreciated and btw the ; is missing in the guide to create luminance database

**Comment by Empornium** [comment]
The exact command changes from OS to OS and which particular package manager you're using (apt-get, apt, aptitude, yum, dnf, emerge etc...) and is outside the scope of the documentation. A quick google should reveal the correct commands though.

We'll fix the missing ; in the INSTALL.md

**Comment by DuR4c3ll** [comment]
Cheer for the reply and I should have made it clear I was using Cent0S 7. Apologies for that.
