### ISSUE TITLE
Apache setup?

### ISSUE THREAD

**Issue by mcangeli** [Empornium/Luminance#13]
I understand that the recommended setup is using nginx for this as the webserver, however for several reasons that isn't possible at this point. 

I've gotten Luminance setup on the server and I can see the files in the directory, however, I am at a point where I need to setup the conf file so that apache knows where to look for the files and I cannot get it set right. 

How do I setup my vhost file in apache in order to get the system working and serving pages correctly? (Is there an example anywhere?)

**Comment by Empornium** [comment]
While this should be possible we do not support Apache and we are not aware of any examples existing. Your options are either to work it out on your own or to resolve the "nginx not available" issue.

If you decide to work it out on your own be aware of the need for the FCGI script path variable and that static assets are served from the public subfolder.

**Comment by mcangeli** [comment]
Bah, then the install guide should not list apache as an option.

**Comment by mcangeli** [comment]
Close this one.
