### ISSUE TITLE
Torrent Upload 502 Error

### ISSUE THREAD

**Issue by mcangeli** [Empornium/Luminance#14]
Perhaps I missed a step, however, I have the site working: https://transhaven.me

And I have radiance installed and running as well. if I log in to the site, I can view the tracker stats via the toolbox.

When I try to upload a torrent as a test though, It goes through and when i hit upload, I get a 502 error.I think I'm missing something (like the location the torrent files go??) but I can't tell and I can't see anything in the setup of the site either. Any help??

**Comment by mcangeli** [comment]
I get a 502 page when it goes to the tools.php page after creating a category as well.

**Comment by Omniusol** [comment]
> 
> 
> I get a 502 page when it goes to the tools.php page after creating a category as well.

The .torrent files are stored in the database.
Did you set your cats in the config.php too?

**Comment by Empornium** [comment]
Sounds like an SQL issue, ensure you have SQL safe mode disabled and if that does not help then we'll need to see what your logs are reporting.

**Comment by mcangeli** [comment]
> > I get a 502 page when it goes to the tools.php page after creating a category as well.
> 
> The .torrent files are stored in the database.
> Did you set your cats in the config.php too?

There is no config.php file? (There's the settings.ini file)

**Comment by Empornium** [comment]
It's not necessary to set torrent categories in settings.ini, that's an old Gazelle thing (when there still was a config.php).

**Comment by mcangeli** [comment]
`2018/10/29 18:35:59 [error] 12267#12267: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  array_values() expects parameter 1 to be array, null given in /var/www/Luminance/application/Services/Render.php on line 507
PHP message: PHP Warning:  Division by zero in /var/www/Luminance/application/Legacy/sections/index/private.php on line 165
PHP message: PHP Warning:  Division by zero in /var/www/Luminance/application/Legacy/sections/index/private.php on line 166
PHP message: PHP Warning:  Division by zero in /var/www/Luminance/application/Legacy/sections/index/private.php on line 167
PHP message: PHP Warning:  Division by zero in /var/www/Luminance/application/Legacy/sections/index/private.php on line 216
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/Luminance/application/Services/Debug.php on line 424" while reading response header from upstream, client: 50.233.145.102, server: transhaven.me, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "transhaven.me", referrer: "https://transhaven.me/login"
2018/10/29 18:36:02 [error] 12267#12267: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  array_values() expects parameter 1 to be array, null given in /var/www/Luminance/application/Services/Render.php on line 507
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/Luminance/application/Services/Debug.php on line 424" while reading response header from upstream, client: 50.233.145.102, server: transhaven.me, request: "GET /tools.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "transhaven.me", referrer: "https://transhaven.me/"
2018/10/29 18:36:08 [error] 12267#12267: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  array_values() expects parameter 1 to be array, null given in /var/www/Luminance/application/Services/Render.php on line 507
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/Luminance/application/Services/Debug.php on line 424" while reading response header from upstream, client: 50.233.145.102, server: transhaven.me, request: "GET /tools.php?action=categories HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "transhaven.me", referrer: "https://transhaven.me/tools.php"
2018/10/29 18:36:26 [error] 12267#12267: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 50.233.145.102, server: transhaven.me, request: "POST /tools.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "transhaven.me", referrer: "https://transhaven.me/tools.php?action=categories"`

**Comment by mcangeli** [comment]
when I upload a torrent, it goes to the 502 error page, but there is nothing in the error log (I turned of the CRIT and its loggin all errors currently).

**Comment by Empornium** [comment]
Do you have PHP set to error on warning?

Connection reset by peer is an interesting one, definitely points to some configuration issue.

**Comment by mcangeli** [comment]
When I turn it on: Warning: array_values() expects parameter 1 to be array, null given in /var/www/Luminance/application/Services/Render.php on line 507

Appears at the top of the page as soon as I log in.
It looks like its looking for info on the seeders/leechers???

**Comment by Empornium** [comment]
That's not going to be the issue, the array issue is fairly innocuous. There's something fundamentally wrong with your configuration somewhere.

**Comment by Omniusol** [comment]
> 
> 
> When I turn it on: Warning: array_values() expects parameter 1 to be array, null given in /var/www/Luminance/application/Services/Render.php on line 507
> 
> Appears at the top of the page as soon as I log in.
> It looks like its looking for info on the seeders/leechers???

Why not take a look at https://github.com/HDInnovations/UNIT3D it may well suit you.

**Comment by panderuowo** [comment]
@Omniusol why even comment that on both our issue threads? Github issues are for reporting issues to better a project, the more problems documented the better the eventual outcome of a project.

**Comment by Omniusol** [comment]
> 
> 
> @Omniusol why even comment that on both our issue threads? Github issues are for reporting issues to better a project, the more problems documented the better the eventual outcome of a project.

Because UNIT3D is better and will work out of the box for you.

**Comment by panderuowo** [comment]
If I were personally interested in UNIT3D I wouldn't be here. The development of Luminance interests me which is why myself and I am sure most other people are here. I took your comment as sarcasm, I apologise if not.

**Comment by mcangeli** [comment]
Ok. Well. I'm going to try reinstalling my server to a clean server and I will try again.

**Comment by mcangeli** [comment]
Bah. 

Even after a clean server install and redoing everything, it errors out (502) when I try to add categories.
The category is added, but after I hit the create button it goes right to the 502 page.

**Comment by Empornium** [comment]
502 is a weird error to throw there, there isn't much to adding a category other than validating the inputs, running a DB query to add it and deleting the category cache items.

Can you confirm which version of PHP, MySQL/MariaDB you're using?

**Comment by panderuowo** [comment]
If it helps I am using php7.0 and haven't faced that issue.

**Comment by mcangeli** [comment]
Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1
Php is 7.0
Nginx is 1.10.3

The luminance config is the default config.

**Comment by mcangeli** [comment]
Ok. I got it. I had missed memcached. Got that installed and its working now. Thanks!

**Comment by Spunkyount** [comment]
> 
> 
> Ok. I got it. I had missed memcached. Got that installed and its working now. Thanks!

may i ask what you missed exactly and how you solved it?
