### ISSUE TITLE
announce URL machine actively refused

### ISSUE THREAD

**Issue by panderuowo** [Empornium/Luminance#15]
Hello, 
everything seems to be running smoothly except my announce URL returns with: "Error: No connection could be made because the target machine actively refused it" any suggestions? Thanks.
I hope I didn't miss anything, I will be going over my configuration and updating if I found the issue but until then any help is appreciated.

**Comment by mcangeli** [comment]
Two questions... 

Did you install a tracker (radiance or ocelot?)
Is your announce port and url set correctly??

**Comment by panderuowo** [comment]
Hi mcangeli!
I opened a new issue under Radiance. I forgot to close this issue, sorry.
