### ISSUE TITLE
Guide for FreeBSD

### ISSUE THREAD

**Issue by ghost** [Empornium/Luminance#19]
There's any specifc guide to FreeBSD? Some of your files mention that you uses that OS.

**Comment by Empornium** [comment]
They do!?

We use Debian.

**Comment by ghost** [comment]
I think the sample of sphinx.conf and the radiance.sysv.init are with FreeBSD style. My mistake

**Comment by Empornium** [comment]
Sphinx config file was adapted over the years, I'm not sure where the original file came from. Radiance's SysV init file was written by one of our developers (On a RedHat based system I think).

I'm sure it's possible to run the software on FreeBSD but I've never actually tried it and I'm not a BSD person. If you do manage to get it working and want to feedback any tips for others then that'd be appreciated but I'm afraid we won't be able help with the BSD aspect of it.

**Comment by ghost** [comment]
If it works, I will return with an guide
