### ISSUE TITLE
file permissions.sql in catalog Luminance/tablespecs/ not found

### ISSUE THREAD

**Issue by kt72ru** [Empornium/Luminance#2]
php application/entry.php setup install
Initializing legacy database table schemas
Initializing ORM database table schemas
Creating table clients
Caught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'Created'
#0 /var/www/html/Luminance/application/Services/DB.php(156): PDOStatement->execute(Array)
#1 /var/www/html/Luminance/application/Services/ORM.php(300): Luminance\Services\DB->raw_query('CREATE TABLE `c...')
#2 /var/www/html/Luminance/application/Services/ORM.php(198): Luminance\Services\ORM->create_table(Array)
#3 /var/www/html/Luminance/application/Builtins/Setup/SetupPlugin.php(83): Luminance\Services\ORM->update_tables()
#4 [internal function]: Luminance\Builtins\Setup\SetupPlugin->install()
#5 /var/www/html/Luminance/application/Core/Controller.php(35): call_user_func_array(Array, Array)
#6 [internal function]: Luminance\Core\Controller->handle_path('install')
#7 /var/www/html/Luminance/application/Core/Master.php(287): call_user_func_array(Array, Array)
#8 [internal function]: Luminance\Core\Master->plugin('Setup', Array)
#9 /var/www/html/Luminance/application/Core/Master.php(264): call_user_func_array(Array, Array)
#10 /var/www/html/Luminance/application/Core/Master.php(153): Luminance\Core\Master->handle_request(Object(Luminance\Core\Request))
#11 /var/www/html/Luminance/application/entry.php(33): Luminance\Core\Master->run()
#12 {main}
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luminance.permissions' doesn't exist in /var/www/html/Luminance/application/Services/DB.php:155
Stack trace:
#0 /var/www/html/Luminance/application/Services/DB.php(155): PDO->prepare('SELECT ID FROM ...')
#1 /var/www/html/Luminance/application/Repositories/PermissionRepository.php(40): Luminance\Services\DB->raw_query('SELECT ID FROM ...')
#2 /var/www/html/Luminance/application/Services/Peon.php(88): Luminance\Repositories\PermissionRepository->getMinUserClassID()
#3 /var/www/html/Luminance/application/Services/Peon.php(136): Luminance\Services\Peon->get_base_variables()
#4 /var/www/html/Luminance/application/Core/Master.php(182): Luminance\Services\Peon->display_page('clierror.html', Array)
#5 /var/www/html/Luminance/application/Core/Master.php(175): Luminance\Core\Master->process_response(Object(Luminance\Responses\Rendered))
#6 /var/www/html/Luminance/application/entry.php(33): Luminance\Core\Master->run()
#7 {main}
  thrown in /var/www/html/Luminance/application/Services/DB.php on line 155

**Comment by Empornium** [comment]
Disable MySQL strict mode, as for permissions.sql, it's not supposed to exist in tablespecs, it's part of the permission entity.

https://github.com/Empornium/Luminance/blob/master/application/Entities/Permission.php

**Comment by kt72ru** [comment]
Thank you. everything is working!
