### ISSUE TITLE
Torrent list issue

### ISSUE THREAD

**Issue by solowas** [Empornium/Luminance#20]
Hello, when a user uploads a torrent they do not show under the torrent section however they do show under the uploads list under profile. 

Here is the sphinx log after running 
> sudo indexer -c /etc/sphinxsearch/sphinx.conf --all

Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/etc/sphinxsearch/sphinx.conf'...
WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: 1 more warnings skipped.
indexing index 'torrents'...
collected 1 docs, 0.0 MB
sorted 0.0 Mhits, 100.0% done
total 1 docs, 125 bytes
total 0.021 sec, 5695 bytes/sec, 45.56 docs/sec
indexing index 'delta'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.013 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'requests'...
WARNING: attribute 'image' not found - IGNORING
WARNING: attribute 'searchtext' not found - IGNORING
collected 0 docs, 0.0 MB
collected 0 attr values
sorted 0.0 Mvalues, 100.0% done
total 0 docs, 0 bytes
total 0.015 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'requests_delta'...
WARNING: attribute 'image' not found - IGNORING
WARNING: attribute 'searchtext' not found - IGNORING
collected 0 docs, 0.0 MB
collected 0 attr values
sorted 0.0 Mvalues, 100.0% done
total 0 docs, 0 bytes
total 0.010 sec, 0 bytes/sec, 0.00 docs/sec
total 10 reads, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg
total 33 writes, 0.001 sec, 5.9 kb/call avg, 0.0 msec/call avg

the on site error is 

Your search did not match anything.

Make sure all names are spelled correctly, or try making your search less specific.

**Comment by Empornium** [comment]
Are you sure Luminance is correctly configured to connect to your sphinx search daemon?

**Comment by solowas** [comment]
[sphinx]
host = 'localhost'
port = 9312
max_matches = 1000
matches_start = 100
matches_step = 50
index = 'torrents'

and all db info in sphinx config is correct

**Comment by Empornium** [comment]
Could also be the cache, IIRC search results get cached for a while.

Edit: also, make sure that the searchd daemon is actually running.

**Comment by solowas** [comment]
restarted cache & searchd, works fine now thanks
