### ISSUE TITLE
User not earning credits freeleech

### ISSUE THREAD

**Issue by solowas** [Empornium/Luminance#21]
This is a record of up/down from the tracker, plus credits awarded
Total    | 0 hrs
Today    | 0 hrs | 0 credits 
Despite seeding, is this caused by freeleech?

**Comment by Empornium** [comment]
No, it's probably caused by your scheduler not running.

**Comment by solowas** [comment]
Schedule returns page or resource does not exist

**Comment by solowas** [comment]
schedule log appears to be fine now, but still no credits. Schedule in toolbox still returns 404

**Comment by Empornium** [comment]
The scheduler needs to be run from the command line. It rewards credits and manages the daily totals, if credits are not being rewarded then there's an issue somewhere with the scheduler. I can't tell you what that issue is as it works fine for us so must be something specific to your installation or configuration.

Some general things to check:
- Are you using the recommended version of PHP (7.0)
- Are you using MariaDB 10.1 or 10.2 ?
- Do you have safe mode disabled on the DB (google it if you're unsure)
- Can you run the command line scheduler manually?
- Are you sure your tracker is working correctly and writing information to the DB?
- Is your tracker in read_only mode?

A scheduler log should look something like this:
```
2018-11-13_01:00:02 1542070801 
2018-11-13_01:00:02 1542070801 Schedule quarter: 0
2018-11-13_01:00:02 1542070801 Running every-time functions
2018-11-13_01:00:07 1542070801 Apply IP range bans
2018-11-13_01:00:12 1542070801 Clearing old IP bans
2018-11-13_01:00:17 1542070801 Award Golden Ducky
2018-11-13_01:00:17 1542070801 to torrents: 
2018-11-13_01:00:22 1542070801 Expire old FL tokens
2018-11-13_01:00:26 1542070801 Update credits
2018-11-13_01:00:43 1542070801 Update connectable status
2018-11-13_01:00:51 1542070801 Remove inactive peers
2018-11-13_01:00:57 1542070801 AutoDelete torrents marked for deletion: On
2018-11-13_01:01:01 1542070801 Delete old speed records
2018-11-13_01:01:06 1542070801 Deleted 0 speed records
2018-11-13_01:01:06 1542070801 -------------------------
2018-11-13_01:01:06 1542070801 
2018-11-13_01:01:06 Scheduler run ended
```

The line saying "Update Credits" is the scheduler awarding credits to users. It won't indicate how many users or how many credits, but if you can see that line then there's a good chance the issue isn't the scheduler but the tracker, if you can't see that line it's likely the scheduler.

**Comment by solowas** [comment]
This is my current log

```
Schedule quarter: 0
Running daily functions
Updating daily site stats
Disable inactive users
Disable unconfirmed
Demote users

Schedule quarter: 1
Running hourly functions
Remove old torrents_files_temp
Find bounties to return
Do the actual bounty returning per user
Remove requests
Include award_badges.php
Record daily seedhours
Update front page snatches
Update front page peer stats
Update front page user stats
Grab stats for promotions
Expire invites
Hide old requests
Remove dead peers
Remove dead sessions
Cleaning up old disabled hits
Various login/warning stats things
Lower request floods
Running daily functions
Updating daily site stats
Disable inactive users
Disable unconfirmed
Demote users

Schedule quarter: 2
Running daily functions
Updating daily site stats
Disable inactive users
Disable unconfirmed
Demote users

Schedule quarter: 3
Find users to disable leeching for
Disable leeching in DB
Disable leeching in tracker
Update Ratio Watch
Running daily functions
Updating daily site stats
Disable inactive users
Disable unconfirmed
Demote users

Schedule quarter: 0
Running daily functions
Updating daily site stats
Disable inactive users
Disable unconfirmed
Demote users

```

my crontab follows

> 0,15,30,45  *  *   *    *       /usr/bin/php /var/application/entry.php schedule >> /root/schedule.log

I assume I don't set a key like other gazelle crontab configs as there is no define in settings.ini.

php7.0, maria 10.1, safe mode disabled, radiance is not in read only mode, tracker is working fine and also did award a golden duck to user fine if that means anything. 
How would I go by running scheduler via command line?

**Comment by Empornium** [comment]
```/usr/bin/php /var/application/entry.php schedule```
 That runs the scheduler, there's no need for a key as unlike Gazelle Luminance understands it's being called from the command line and has its own access policies for such.

It looks like your instance isn't remembering which scheduled tasks have been run and which haven't. You can see that it's running daily functions every time rather than once per day for instance. Log into your DB and check to see if the schedule table is empty (I bet it is). Assuming that table is in fact empty then insert a blank row like this:

```INSERT INTO schedule () VALUES()```

That should allow the scheduler to run the correct tasks and hopefully start awarding credits.

**Comment by solowas** [comment]
The table was infact empty and now it seems to be working on the correct schedule however that didn't resolve the issue. 
And when I try executing 
> /usr/bin/php /var/www/application/entry.php schedule

I get this:

```
Schedule quarter: 0
Running every-time functions
Apply IP range bans
Caught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Netmask' in 'field list'
#0 /var/www/application/Services/DB.php(181): PDOStatement->execute()
#1 /var/www/application/Services/OldDB.php(36): Luminance\Services\DB->legacy_query('INSERT INTO ips...')
#2 /var/www/application/Legacy/sections/schedule/index.php(1217): Luminance\Services\OldDB->query('INSERT INTO ips...')
#3 /var/www/application/Core/LegacyHandler.php(41): require('/var/www/applic...')
#4 /var/www/application/Core/LegacyHandler.php(18): Luminance\Core\LegacyHandler->load_section('schedule')
#5 /var/www/application/Core/Master.php(306): Luminance\Core\LegacyHandler->handle_legacy_request('schedule')
#6 [internal function]: Luminance\Core\Master->legacy('schedule')
#7 /var/www/application/Core/Master.php(276): call_user_func_array(Array, Array)
#8 /var/www/application/Core/Master.php(161): Luminance\Core\Master->handle_request(Object(Luminance\Core\Request))
#9 /var/www/application/entry.php(34): Luminance\Core\Master->run()
#10 {main}
PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/application/Services/Render.php:206
Stack trace:
#0 /var/www/application/Services/Render.php(519): Luminance\Services\Render->get_scripts('')
#1 /var/www/application/Services/Render.php(159): Luminance\Services\Render->get_header_vars(Array)
#2 /var/www/application/Core/Master.php(187): Luminance\Services\Render->display_page('clierror.html.t...', Array, NULL)
#3 /var/www/application/Core/Master.php(181): Luminance\Core\Master->process_response(Object(Luminance\Responses\Rendered))
#4 /var/www/application/entry.php(34): Luminance\Core\Master->run()
#5 {main}
  thrown in /var/www/application/Services/Render.php on line 206

```

There was another error previously but I didn't get to catch the error and i'm not sure what changed to reproduce it

**Comment by Empornium** [comment]
Replace the scheduler's range ban query with the following:
```
//------------- Apply IP range bans to curb brute force attacks quicker ------//
# TODO only works on IPv4, upgrade to work with IPv6 too
print("Apply IP range bans\n");
$DB->query("INSERT INTO ips (StartAddress, EndAddress, BannedUntil, Banned, Reason)
               (SELECT  (ip.StartAddress & 0xFFFF0000) AS StartAddress,
                        (ip.StartAddress | 0x0000FFFF) AS EndAddress,
                        DATE_ADD(NOW(), INTERVAL 8 hour) AS BannedUntil,
                        true AS Banned,
                        'brute force' AS Reason
                  FROM request_flood AS rf
                  JOIN ips AS ip ON ip.ID=rf.IPID
                 WHERE LastRequest >= DATE_SUB(NOW(), INTERVAL 1 DAY)
              GROUP BY StartAddress
                HAVING  COUNT(INET_ATON(INET6_NTOA(ip.StartAddress)) & 0xFFFF0000) > 10)
            ON DUPLICATE KEY UPDATE BannedUntil=DATE_ADD(NOW(), INTERVAL 8 hour)
           ");
sleep(5);
```

**Comment by solowas** [comment]
Fixed the issue, thanks.
