### ISSUE TITLE
unable to get torrent file to show 

### ISSUE THREAD

**Issue by cbtrident** [Empornium/Luminance#23]
am sorry this may be my fault but when i got to the list torrent page it does not show any of the torrent file.
i check the log file and am getting this error
2018/12/21 19:43:30 [error] 4374#4374: *7327 FastCGI sent in stderr: "PHP message: PHP Warning:  date() expects parameter 2 to be integer, string given in /var/www/html/Luminance/application/Services/Debug.php on line 412" while reading response header from upstream, client: 192.168.1.84, server: test.4thd.xyz, request: "GET /torrents.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "test.4thd.xyz", referrer: "http://test.4thd.xyz/torrents.php

so am hopping some one can say what to do to fix
or could i ask what linux os should i use as this is ubuntu 16.04
i have most of it working and database for a old gazelle site import with no problem
just not showing torrent

**Comment by Empornium** [comment]
You need to install and configure sphinxsearch.
