### ISSUE TITLE
Invites not sending out

### ISSUE THREAD

**Issue by slavanomics** [Empornium/Luminance#24]
Sending out an invite hangs until hitting a gateway timeout

Running:
Ubuntu 18.04
MariaDB 10.1

**Comment by Empornium** [comment]
Anything in the error log?

**Comment by slavanomics** [comment]
`2019/01/22 14:24:20 [error] 12319#12319: *6943 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.0.1, server: tracker.censored.com, request: "POST /users/1/invite/send HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock", host:"tracker.censored.com", referrer: "https://tracker.censored.com/users/1/invite"`

This is the only issue i'm having, everything else works fine

**Comment by Empornium** [comment]
nothing in the PHP error logs?

**Comment by slavanomics** [comment]
Nothing from what I can tell

**Comment by slavanomics** [comment]
Tracked down the issue to postfix and SMTP.

**Comment by Empornium** [comment]
Glad you got it solved. :)
