### ISSUE TITLE
Error 500 Internal

### ISSUE THREAD

**Issue by XJOSCOX** [Empornium/Luminance#29]
I use PHP 7.0.33-0+deb9u3
MariaDB 10.1.38
Nginx 1.10.3

I got this error for every requests
Like if I want to see registration log I got

Error 500 Internal

PHP message: PHP Warning:  date() expects parameter 2 to be integer, string given in /var/www/html/Luminance/application/Services/Debug.php on line 412" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.xxx.xxx, request: "GET /tools.php?action=registration_log HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx.xxx.xxx.xxx", referrer: "http://xxx.xxx.xxx.xxx/tools.php"
2019/05/08 01:16:31 [error] 17222#17222: *47 FastCGI sent in stderr: "PHP message: Caught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm.Email' in 'field list'
#0 /var/www/html/Luminance/application/Services/DB.php(180): PDO->prepare('SELECT\n    SQL_...')
#1 /var/www/html/Luminance/application/Services/OldDB.php(36): Luminance\Services\DB->legacy_query('SELECT\n    SQL_...')
#2 /var/www/html/Luminance/application/Legacy/sections/tools/data/registration_log.php(40): Luminance\Services\OldDB->query('SELECT\n    SQL_...')
#3 /var/www/html/Luminance/application/Legacy/sections/tools/index.php(642): include('/var/www/html/L...')
#4 /var/www/html/Luminance/application/Core/LegacyHandler.php(41): require('/var/www/html/L...')
#5 /var/www/html/Luminance/application/Core/LegacyHandler.php(18): Luminance\Core\LegacyHandler->load_section('tools')
#6 /var/www/html/Luminance/application/Core/Master.php(306): Luminance\Core\LegacyHandler->handle_legacy_request('tools')
#7 [internal function]: Luminance\Core\Master->legacy('tools')
#8 /var/www/html/Luminance/appl...
PHP message: PHP Warning:  date() expects parameter 2 to be integer, string given in /var/www/html/Luminance/application/Services/Debug.php on line 412" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.xxx.xxx, request: "GET /tools.php?action=registration_log HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx.xxx.xxx.xxx", referrer: "http://xxx.xxx.xxx.xxx/tools.php"

**Comment by Empornium** [comment]
Run this SQL:

```
ALTER TABLE users_main ADD COLUMN `Email` varchar(255) NOT NULL;
```
