### ISSUE TITLE
0.6 Release

### ISSUE THREAD

**Issue by Omniusol** [Empornium/Luminance#30]
It's been a very long time since the last release with no sight of 0.6 release. Is this still under development or has the project been abandoned? If not is there an ETA for 0.6 release?

**Comment by Empornium** [comment]
Yes, we are still developing the code privately. Public releases occur only when the code is deemed stable... well, maybe just deemed not unstable... okay, not explosively volatile. :-)

We've very recently moved the majority of the forums over to TWIG templating but this is not yet public as a lot of background code required modification to support this. Once the forums are 100% under TWIG and PDO we'll stabilize the code and release.

0.6 is a *HUGE* milestone and is honestly likely to take a couple of years, and it's entirely possible that 0.6 and 0.7 will be swapped around.
