### ISSUE TITLE
cli error

### ISSUE THREAD

**Issue by Kufirc** [Empornium/Luminance#31]
hello
I would like to ask what the error is? how can I re-integrate my users into the old database?

image:
https://kepkuldes.com/images/9838f7096d8150963a7c9f0e0b66b196.png

**Comment by Empornium** [comment]
What did you set as the site's URL during the configuration stage?

**Comment by Kufirc** [comment]
[main]
site_name = 'localhost'
; (was: SITE_NAME)
nonssl_site_url = 'localhost'
; (was: NONSSL_SITE_URL)
ssl_site_url = 'localhost'
; (was: SSL_SITE_URL)
;site_ip = ''
; (was: SITE_IP)
announce_url = 'http://localhost:2710'
; (was: ANNOUNCE_URL; gets derived from nonssl_site_url and the [tracker] port setting by default)
nonssl_static_server = 'public/static/'
; (was: NONSSL_STATIC_SERVER)
ssl_static_server = 'public/static/'
; (was: SSL_STATIC_SERVER)
site_url = 'localhost'
; (was: SITE_URL)
static_server = 'public/static/'
; (was: STATIC_SERVER)
;additional_domains = 'somelinkedsite.com,anotherlinkedsite.com'
internal_urls_regex = '@^https?:\/\/localhost\/|^https?:\/\/\/@'
non_anon_urls_regex = '@^https?:\/\/localhost|^https?:\/\/@'
; (was: INTERNAL_URLS_REGEX)
non_anon_domains = 'friendly.site.sx,imagehost.somelinkedsite.com'
;non_anon_urls_regex = ''


SetupPlugin.php 25  
 [ 'CLI',  'fixUser/**',       0, 'migrateUser' ],

are there migrate users that migrate users from the old gazelle database to the luminance users table?

**Comment by Empornium** [comment]
```
nonssl_site_url = 'localhost'
ssl_site_url = 'localhost'
```
Those are not FQDN and thus fail validation when used to create an email address. Try something like localhost.localdomain, or add a distinct name to your hosts file.

> are there migrate users that migrate users from the old gazelle database to the luminance users table?

Yes, follow the migrate instructions instead of the install instructions.

**Comment by Empornium** [comment]
https://github.com/Empornium/Luminance/blob/master/INSTALL.md

To migrate from Gazelle, cd into the Luminance directory and run these commands:
```
php application/entry.php setup configure ../../path/to/gazelle/classes/config.php
php application/entry.php setup upgrade

**Comment by Kufirc** [comment]
oke thanks

**Comment by Kufirc** [comment]
[04-Jul-2019 17:38:48 Europe/Budapest] Caught Luminance\Errors\ConfigurationError: Settings file: C:\Winginx\home\localhost\public_html\application/settings.ini already exists!
#0 C:\Winginx\home\localhost\public_html\application\Services\Settings.php(325): Luminance\Services\Settings->write_settings_file('; Settings whic...')
#1 C:\Winginx\home\localhost\public_html\application\Plugins\Setup\SetupPlugin.php(90): Luminance\Services\Settings->generateConfig(Array)
#2 [internal function]: Luminance\Plugins\Setup\SetupPlugin->configure('config.php')
#3 C:\Winginx\home\localhost\public_html\application\Core\Controller.php(38): call_user_func_array(Array, Array)
#4 [internal function]: Luminance\Core\Controller->handle_path('configure', 'config.php')
#5 C:\Winginx\home\localhost\public_html\application\Core\Master.php(299): call_user_func_array(Array, Array)
#6 [internal function]: Luminance\Core\Master->plugin('Setup', Array, 'config.php')
#7 C:\Winginx\home\localhost\public_html\application\Core\Master.php(276): call_user_func_array(Array, Array)
#8 C:\Winginx\home\localhost\public_html\application\Core\Master.php(161): Luminance\Core\Master->handle_request(Object(Luminance\Core\Request))
#9 C:\Winginx\home\localhost\public_html\application\entry.php(34): Luminance\Core\Master->run()
#10 {main}

**Comment by Empornium** [comment]
Yeah, delete your old settings.ini file first. It won't overwrite a settings file, just in case.

**Comment by Kufirc** [comment]
ááááá   :)  

:(
image

https://p1.picsto.re/KzPW6.png
datatime  format problem?

**Comment by Empornium** [comment]
:-\

> datatime format problem?

No, it's the fact that the auto-increment column is being declared as null, but that doesn't happen on my instance.

Run this SQL manually:
```
ALTER TABLE `invites` ADD COLUMN `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
MODIFY COLUMN `InviteKey` VARCHAR(255) NULL,
MODIFY COLUMN `Expires` DATETIME DEFAULT '0000-00-00 00:00:00'
DROP PRIMARY KEY,
ADD PRIMARY KEY (`ID`);
```

If it complains about the Expires column and DATETIME then just default it to null instead.

**Comment by Empornium** [comment]
Alternatively, replace line 606 of application/Services/ORM.php with:

```
# Cannot be null if primary or auto-increment
$auto_increment = array_key_exists('auto_increment', $options) ? $options['auto_increment'] : false;
$primary = array_key_exists('primary', $options) ? $options['primary'] : false;
$options['nullable'] = !($auto_increment || $primary);
```

I think that should fix the null issues for you.

**Comment by Kufirc** [comment]
ok test  ....   thanks   help  :)

**Comment by Kufirc** [comment]
no migrate :( 

https://p1.picsto.re/y0Nbx.png

**Comment by Empornium** [comment]
You'll need to locate each bad email and fix them in the DB... or change the code to decide how you want to handle such cases.

You can call upgrade multiple times, it should start where it finished on the last run.

**Comment by Kufirc** [comment]
which php file should be modified to run migrate and ignore faulty emails?

**Comment by Empornium** [comment]
application/Plugins/Setup/SetupPlugin.php

migrateUser function, line 305. There's already a try/catch in there, so you'll need to look at the emails it's rejecting and determine how to handle that specific case.

**Comment by Kufirc** [comment]
can't you log which email address is wrong?

**Comment by Kufirc** [comment]
https://p1.picsto.re/tT67K.png

in this case what email is not good?

all users test mail ....

**Comment by Kufirc** [comment]
setting.ini  bad mail?

**Comment by Empornium** [comment]
Okay, so emails must be unique. Having every user take the same email is going to cause the emailManager to throw an exception on line 322 of SetupPlugin, that exception will be caught on line 330 and then SetupPlugin will try to invent an email for that user and save it on line 331. The invented email takes the format username@site_url, if you still have localhost as the site url then that email will be like user@localhost and you're back to the same issue as before.

As a quick fix, you could modify the users_main table to give all users a unique and (hopefully) valid email, like: 

```
UPDATE `users_main`  SET `Email`=CONCAT(`Username`, '@kufirc.com');
```

Remember, this is not a fix that your users will appreciate so if you're going to use Luminance in production then you need to properly import the emails at some point.

**Comment by Empornium** [comment]
Also, you just leaked you user's usernames and IPs with that screenshot...

**Comment by Kufirc** [comment]
[21-Nov-2019 07:33:19 UTC] Caught Luminance\Errors\ConfigurationError: Settings file: C:\Winginx\home\localhost\public_html\application/settings.ini already exists!
#0 C:\Winginx\home\localhost\public_html\application\Services\Settings.php(325): Luminance\Services\Settings->write_settings_file('; Settings whic...')
#1 C:\Winginx\home\localhost\public_html\application\Plugins\Setup\SetupPlugin.php(90): Luminance\Services\Settings->generateConfig(Array)
#2 [internal function]: Luminance\Plugins\Setup\SetupPlugin->configure('config.php')
#3 C:\Winginx\home\localhost\public_html\application\Core\Controller.php(38): call_user_func_array(Array, Array)
#4 [internal function]: Luminance\Core\Controller->handle_path('configure', 'config.php')
#5 C:\Winginx\home\localhost\public_html\application\Core\Master.php(299): call_user_func_array(Array, Array)
#6 [internal function]: Luminance\Core\Master->plugin('Setup', Array, 'config.php')
#7 C:\Winginx\home\localhost\public_html\application\Core\Master.php(276): call_user_func_array(Array, Array)
#8 C:\Winginx\home\localhost\public_html\application\Core\Master.php(161): Luminance\Core\Master->handle_request(Object(Luminance\Core\Request))
#9 C:\Winginx\home\localhost\public_html\application\entry.php(34): Luminance\Core\Master->run()
#10 {main}

**Comment by Empornium** [comment]
Yeah, the software won't overwrite an existing settings file. When generating a settings file Luminance will generate a set of encryption keys, these keys are used for a number of things including when storing some content in the database. If you accidentally overwrite these keys then some of your data will be inaccessible.  
  
When migrating a config.php like you are trying to do *SOME* of they encryption keys already exist, but not all of them, so it isn't even safe to allow reimports.  
  
Either delete the existing settings.ini or better yet move it out the way to settings.ini.bak or some similar name (maybe include the date or something).

**Comment by Kufirc** [comment]
whatever I do for god he doesn't want to succeed

is there no easier way to do this migration?

**Comment by Empornium** [comment]
Not really. The software is marked as Beta for a reason.

**Comment by Kufirc** [comment]
We managed to migrate the users table but converted the password in an interesting way:

$-Salted md5 = $ MmtkcDhheXB4YnY0cW01MWpkaHlpOTYxYWZxYml0bXo $ Sk3BV96mR4A4LW1U9nLwtg ==

every field salted-md5 starts this normal?

**Comment by Empornium** [comment]
I don't know how your modifications work so cannot answer that question.

**Comment by Kufirc** [comment]
if (strlen ($ oldUser ['PassHash']) === 32) {
                     if (! empty ($ oldUser ['Secret'])) {
                         $ user-> Password = "\ $ salted-md5 \ $ {$ encodedSecret} \ $ {$ encodedHash}";
                     } else {
                         $ user-> Password = "\ $ md5 \ $ {$ encodedSecret} \ $ {$ encodedHash}";
                     }

SetupPlugin.php 360-370 sort

**Comment by Empornium** [comment]
https://www.php.net/manual/en/function.password-hash.php

**Comment by Kufirc** [comment]
ok tanks :)
