### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by haig233** [Empornium/Luminance#33]
When I install according to the INSTALL.md file, the browser appears 502 Bad Gateway error

PHP：
```
PHP 7.3.11 (cli) (built: Nov  8 2019 19:34:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
```

Nginx :
nginx version: nginx/1.16.1

Mysql:
mysql  Ver 14.14 Distrib 5.6.44, for Linux (x86_64) using  EditLine wrapper

**Comment by Empornium** [comment]
You need to ensure you're pointing to the correct place for connection to PHP-FPM, the nginx config shows:
```fastcgi_pass 127.0.0.1:9000;```
That's default on most distributions but some use a unix socket instead, for instance, RedHat distributions (RHEL, Fedora, CentOS, etc) use a unix socket and it's located at /run/php-fpm/www.sock, so the correct fastcgi_pass directive would be:
```fastcgi_pass unix:///run/php-fpm/www.sock;```
