### ISSUE TITLE
502 Bad Gateway on new install

### ISSUE THREAD

**Issue by Spunkyount** [Empornium/Luminance#34]
I have check the error logs both nginx and php all is well.
Any idea why I am getting 502 Bad Gateway
My nginx conf is in /etc/nginx/sites-available and /etc/nginx/sites-enabled
I used the example conf you provided.

Thanks

**Comment by Empornium** [comment]
Are you sure PHP is listening on an internet socket and not a unix socket?

**Comment by Spunkyount** [comment]
Not sure how I missed that. Thanks.
