### ISSUE TITLE
Bots are forbidden

### ISSUE THREAD

**Issue by Spunkyount** [Empornium/Luminance#36]
I'm unable to login.

[Bots are forbidden](https://i.imgur.com/pttRJcX.png)

Ah I see the exact path in the nginx.conf should be **/var/www/Luminance/public**

My issue was I had **/var/www/Luminance**

Sorry about that.

**Comment by Kufirc** [comment]
https://github.com/Empornium/Luminance/issues/55
did you only modify the path?

**Comment by Kufirc** [comment]
solved
