### ISSUE TITLE
MemcachePool

### ISSUE THREAD

**Issue by Spunkyount** [Empornium/Luminance#37]
**Warning: MemcachePool::getstats(): Invalid stats type in /opt/Luminance/application/Services/Cache.php on line 85**

I happened to turn or display errors and see this any ideas? Memcahed seems to be running I have checked.

And in **tools.php?action=service_stats** I see

**Warning: Division by zero in /opt/Luminance/application/Legacy/sections/tools/data/service_stats.php**

**Comment by Empornium** [comment]
service_stats still expects the cache to use the old memcache extension. This'll get fixed with the next update but can be ignored for now.

**Comment by Spunkyount** [comment]
May I ask when the next update will be? Basically memcache  is still working correctly in the meantime?

**Comment by Empornium** [comment]
When it's ready, hopefully the first quarter of 2020 but no guarantees.
