### ISSUE TITLE
logrotate.conf

### ISSUE THREAD

**Issue by Spunkyount** [Empornium/Luminance#38]
**CentOS Linux release 7.7.1908 (Core)
10.1.43-MariaDB
PHP 7.0.33 (cli)** 

Hi, where should the logrotate.conf be placed exactly? I'm kinda puzzled by this one.

Thanks

**Comment by Empornium** [comment]
/etc/logrotate.d/

https://www.tecmint.com/install-logrotate-to-manage-log-rotation-in-linux/

**Comment by Spunkyount** [comment]
Thanks for that. I assume now that I just need to edit the current **/etc/lograte.conf** and add to it the contents of your example **/etc/lograte.conf** is that correct?

```# see "man logrotate" for details
# rotate log files weekly
weekly

# keep 4 weeks worth of backlogs
rotate 4

# create new (empty) log files after rotating old ones
create

# use date as a suffix of the rotated file
dateext

# uncomment this if you want your log files compressed
#compress

# RPM packages drop log rotation information into this directory
include /etc/logrotate.d

# no packages own wtmp and btmp -- we'll rotate them here
/var/log/wtmp {
    monthly
    create 0664 root utmp
	minsize 1M
    rotate 1
}

/var/log/btmp {
    missingok
    monthly
    create 0600 root utmp
    rotate 1
}

# system-specific logs may be also be configured here.

/var/log/luminance/*.log {
        daily
        missingok
        rotate 52
        compress
        delaycompress
        notifempty
        create 640 nginx nginx
}```

**Comment by Empornium** [comment]
You can do that but it's not recommended, simply put the luminance logrotate.conf file into the logrotate.d directory and name it appropriately.
