### ISSUE TITLE
PHP >= 7.0 Repo

### ISSUE THREAD

**Issue by Spunkyount** [Empornium/Luminance#39]
There are a few repos for PHP >= 7.0 but the problem is 7.0 is no longer supported. Can you please suggest a repo to use for Centos?

Thanks

**Comment by Empornium** [comment]
What site is this for?

**Comment by Spunkyount** [comment]
It is not for a site at the right now. I am just trying to get it working for the moment.

**Comment by Empornium** [comment]
Well, I don't intend to sound mean here, but maybe you should find a friend that has some experience running web sites, you seem to be asking quite a lot of basic questions and that doesn't exactly bode well.

**Comment by Spunkyount** [comment]
I understand. I don't plan to change anything at all in the code. It is quite fine as it is. It is very difficult to trust anyone online. I know that PHP 7.2 is distributed with Centos 8 which is why I asked you to suggest a repo for PHP 7.0. I know there is webstatic and remi for example.

**Comment by Empornium** [comment]
I wouldn't recommend installing a third party repository unless it's from an official source. If PHP provides a CentOS repository then I'd recommend that. That said, I think it should work fine with PHP 7.2, if not then the next Luminance release (currently scheduled for first quarter 2020) supports 7.1, 7.2, 7.3 & experimental support for 7.4.

**Comment by Spunkyount** [comment]
Wow that is amazing to know and I shall try to install PHP 7.2 which is supported. Thank you for taking the time to explain.

**Comment by Spunkyount** [comment]
> 
> 
> Well, I don't intend to sound mean here, but maybe you should find a friend that has some experience running web sites, you seem to be asking quite a lot of basic questions and that doesn't exactly bode well.

Myself and a couple of other cool guys are wanting to get a site going based on MySpleen to fill the void left by a similar site that went away recently. At the moment there is three of us and hopefully we could find a few more interested to be a part of the staff team. If you're interested in setting us up securely  on a brand new clean install of Centos 8 that would be great! My email is spunkyount.github@protonmail.com if you want to get in touch.

**Comment by Empornium** [comment]
Lets not do email, jump on Emp's IRC and we can chat.
