### ISSUE TITLE
PHP Parse error on Installation

### ISSUE THREAD

**Issue by executivoclub** [Empornium/Luminance#4]
Hello Guys,

I'm facing a problem when I do the configure command:

`PHP Parse error:  syntax error, unexpected '.' in /var/www/Luminance/application/Services/Cache.php on line 129

same error in line 148

other erros unexpected * when I remove the dotz from the lines showed.`

Maybe it's an old version of composer?

Regards

**Comment by Empornium** [comment]
You need PHP 5.6 minimum as documented in INSTALL.md, this error is because you're trying to run it on too low a version. It should work fine on PHP 5.6 but we recommend PHP 7.0.
