### ISSUE TITLE
PHP 7.2 Fatal Error

### ISSUE THREAD

**Issue by Spunkyount** [Empornium/Luminance#40]
`Fatal error: Uncaught Error: [] operator not supported for strings in /var/www/Luminance/application/Services/Render.php:206 Stack trace: #0 /var/www/Luminance/application/Services/Render.php(519): Luminance\Services\Render->get_scripts('') #1 /var/www/Luminance/application/Services/Render.php(159): Luminance\Services\Render->get_header_vars(Array) #2 /var/www/Luminance/application/Core/Master.php(187): Luminance\Services\Render->display_page('@Authentication...', Array, NULL) #3 /var/www/Luminance/application/Core/Master.php(162): Luminance\Core\Master->process_response(Object(Luminance\Responses\Rendered)) #4 /var/www/Luminance/application/entry.php(34): Luminance\Core\Master->run() #5 {main} thrown in /var/www/Luminance/application/Services/Render.php on line 206`

Hope this is helpful to you:

I edited **render.php** I changed:

**Lines 206 and 207 to:**

> $extra_scripts = 'svg-injector'; // handles icon injections
>         $extra_scripts = 'prism';        // handles code syntax highlighting

**Line 209 to:**

> foreach ((array) $extra_scripts as $extra_script) {

I am not even 100% sure that is a correct fix but I now see the login page with no errors 🙍 
Now I am logged in it is still throwing errors. I think at this point I will just have to give up and call it a day.

**Comment by Empornium** [comment]
It's not the correct fix, no. The problem is a string is being passed to the function when it expects an array, you need to ensure that only an array is passed. Add the following code just above line 206.

```
        # Ensure that $extraScripts is an array
        if (!is_array($extraScripts)) {
            $extraScripts = [];
        }
```
