### ISSUE TITLE
Stylesheets

### ISSUE THREAD

**Issue by Spunkyount** [Empornium/Luminance#41]
Hi, I can't see a stylesheets.sql file in /Luminance/tablespecs and tb I don't want all those stylsheets. Any way to choose which ones to use at install time there?

**Comment by Empornium** [comment]
Stylesheets use an entity. There's no way to choose at install time nor is there a tool to modify them later, you'll need to modify the DB contents manually.

**Comment by Spunkyount** [comment]
Okay thanks for the reply.
