### ISSUE TITLE
400 No userclasses have been configured.

### ISSUE THREAD

**Issue by Spunkyount** [Empornium/Luminance#42]
I attemped to create a new user class in /tools.php?action=create_user and it fails with the error as shown in the title of this issue.

I did see https://github.com/Empornium/Luminance/issues/28 it helps to a degree.
In my own **settings.ini** I have:

> [users]
> classes = 'APPRENTICE=2,PERV=3,GOOD_PERV=4,DONOR=20,SEXTREME_PERV=5,SMUT_PEDDLER=6,ADMIN=1,SYSOP=15'
> level_staff = 500
> level_admin = 600

So I assumed that if level_admin = 600 then I should use a new number for the entry user class something like 100 as show [here](https://i.imgur.com/WtzbIXE.png)

Can you advise where I am going awry, please?

**Comment by Empornium** [comment]
Create user creates a user not a user class. The default class on creation is the class with the lowest level which has been configured for auto-promotion. If no classes have been configured for auto promotion then the site has no way of knowing which class should be applied to new users.

**Comment by Spunkyount** [comment]
Thanks for the explanation.

**Comment by Kufirc** [comment]
hello

/application/Services/Auth.php  line 675   

$permissionID = 1;
change 
$permissionID = 2;
