### ISSUE TITLE
Site not sending emails

### ISSUE THREAD

**Issue by Spunkyount** [Empornium/Luminance#43]
Had a look in the issues and run a SQL you advised someone else **ALTER TABLE users_main ADD COLUMN `Email` varchar(255) NOT NULL;**

Site is setup to send email via Postfix and it sends test emails from the terminal with the command:

**echo "Testing this email" | mail -s "Testing this email" user@domain.com**

Check both DKIM and SPF on https://mxtoolbox.com all green no errors.
Checked the site logs nothing in there all is well.
Any idea what I am missing at all?

**Comment by Spunkyount** [comment]
I do see in settings.ini 

**mail_domain = example.com**

obviously it doesn't really say example.com i just don't want to show the world my domain.

Right now I'm under the assumption that the site doesn't actually send out any email, right? It just requires a valid email to register? If so this is indeed very cool. Makes server security even better! Am I right?

**Comment by Spunkyount** [comment]
Any update for me on this m8?

**Comment by Empornium** [comment]
Site will not send email while in debug mode. Otherwise, it should "just work"

**Comment by Spunkyount** [comment]
You're a lovely fella. I can't believe I forgot that debug was **On**
I guess I'm dumb like really dumb for real.
[Works](https://i.imgur.com/cl7vetA.png) great, now.
Cheers for that.
