### ISSUE TITLE
HTTP 500 ERROR

### ISSUE THREAD

**Issue by haig233** [Empornium/Luminance#44]
Hello i encountered some errors

PHP Warning:  time() expects exactly 0 parameters, 6 given in /home/wwwroot/Luminance/application/Legacy/sections/schedule/index.php on line 43
PHP Warning:  time() expects exactly 0 parameters, 6 given in /home/wwwroot/Luminance/application/Legacy/sections/schedule/index.php on line 36
PHP Warning:  time() expects exactly 0 parameters, 6 given in /home/wwwroot/Luminance/application/Legacy/sections/schedule/index.php on line 36
PHP Warning:  Use of undefined constant GREAT_PERV - assumed 'GREAT_PERV' (this will throw an Error in a future version of PHP) in /home/wwwroot/Luminance/application/Legacy/sections/schedule/index.php on line 741
PHP Warning:  Use of undefined constant GREAT_PERV - assumed 'GREAT_PERV' (this will throw an Error in a future version of PHP) in /home/wwwroot/Luminance/application/Legacy/sections/schedule/index.php on line 772
PHP Warning:  Use of undefined constant GREAT_PERV - assumed 'GREAT_PERV' (this will throw an Error in a future version of PHP) in /home/wwwroot/Luminance/application/Legacy/sections/schedule/index.php on line 802
Caught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'GREAT_PERV' in 'where clause'
#0 /home/wwwroot/Luminance/application/Services/DB.php(180): PDO->prepare('SELECT ID FROM ...')
#1 /home/wwwroot/Luminance/application/Services/OldDB.php(36): Luminance\Services\DB->legacy_query('SELECT ID FROM ...')
#2 /home/wwwroot/Luminance/application/Legacy/sections/schedule/index.php(802): Luminance\Services\OldDB->query('SELECT ID FROM ...')
#3 /home/wwwroot/Luminance/application/Core/LegacyHandler.php(41): require('/home/wwwroot/L...')
#4 /home/wwwroot/Luminance/application/Core/LegacyHandler.php(18): Luminance\Core\LegacyHandler->load_section('schedule')
#5 /home/wwwroot/Luminance/application/Core/Master.php(306): Luminance\Core\LegacyHandler->handle_legacy_request('schedule')
#6 [internal function]: Luminance\Core\Master->legacy('schedule')
#7 /home/wwwroot/Luminance/application/Core/Master.php(276): call_user_func_array(Array, Array)
#8 /home/wwwroot/Luminance/application/Core/Master.php(161): Luminance\Core\Master->handle_request(Object(Luminance\Core\Request))
#9 /home/wwwroot/Luminance/application/entry.php(34): Luminance\Core\Master->run()
#10 {main}
PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /home/wwwroot/Luminance/application/Services/Render.php:206
Stack trace:
#0 /home/wwwroot/Luminance/application/Services/Render.php(519): Luminance\Services\Render->get_scripts('')
#1 /home/wwwroot/Luminance/application/Services/Render.php(159): Luminance\Services\Render->get_header_vars(Array)
#2 /home/wwwroot/Luminance/application/Core/Master.php(187): Luminance\Services\Render->display_page('clierror.html.t...', Array, NULL)
#3 /home/wwwroot/Luminance/application/Core/Master.php(181): Luminance\Core\Master->process_response(Object(Luminance\Responses\Rendered))
#4 /home/wwwroot/Luminance/application/entry.php(34): Luminance\Core\Master->run()
#5 {main}
  thrown in /home/wwwroot/Luminance/application/Services/Render.php on line 206

PHP7.3
MYSQL5.6

**Comment by Empornium** [comment]
Only PHP 7.0 is supported by the current release, hence the errors from the time function. As for the undefined constants, you need to configure your classes in settings.ini and/or modify the scheduler to use different class constants.
