### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by Kufirc** [Empornium/Luminance#46]
server {
	listen 80;
    charset UTF-8;
	server_name kufirc;

	access_log off;

	root C:\Winginx/home/localhost/public_html;
	index index.php index.html index.htm;

	location / {
		try_files $uri /index.php?$args;
	}

	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_index index.php;

		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME C:\Winginx/home/localhost/public_html/application/entry.php;
		
	}
}

**Comment by Kufirc** [comment]
2020/03/22 19:07:59 [error] 2100#4284: *1 upstream timed out (10060: FormatMessage() error:(15105)) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"


error log

**Comment by Empornium** [comment]
I have no idea how to configure Nginx/PHP on Windows, but this is obviously not an issue with Luminance.
