### ISSUE TITLE
Composer installed in folder, but still asking for it

### ISSUE THREAD

**Issue by executivoclub** [Empornium/Luminance#47]
Hello,

I'm trying to install the Luminance, but after follow all the steps, download composer to Luminance directory, when I execute the command: 
`php application/entry.php setup configure`

I getting the follow message:
`You must install composer to use this software, please read INSTALL.md for details`

Composer is installed on the Luminance directory, not running as root.

Anyone faced this problem before?

**Comment by Empornium** [comment]
You missed a step: ```php composer.phar install```

**Comment by executivoclub** [comment]
I've made this in the Luminance directory, but need to do that on the application folder also?

**Comment by executivoclub** [comment]
> You missed a step: `php composer.phar install`

I've execute this command in the Luminance folder, but the error is on the application folder, got the same message if I run it on the application/ folder.

**Comment by Empornium** [comment]
Composer should be installed in the top level directory, if you've done it right there will be a vendor directory next to the application directory. Inside vendor should be a bunch of other directories.

Luminance will only throw this error if it cannot locate the composer autoloader (vendor/autoload.php), which means composer is not correctly installed.
