### ISSUE TITLE
Users unable to connect to each other.

### ISSUE THREAD

**Issue by poorplanet** [Empornium/Luminance#48]
I have both Luminance and Radiance up and running. The "ocelot_info" page is populating information, clients are able to announce successfully to the tracker, but no one has been able to download from each other. Along with this, torrents are listed as having zero peers and seeds on the website.  Any recommendations on where I would start troubleshooting this?

**Comment by Empornium** [comment]
Sounds like those announces are not actually making it to the tracker at all.

**Comment by poorplanet** [comment]
We just had a file go through successfully, but most clients are still stalled: https://i.imgur.com/rtiWeGw.png

Radiance.log is showing several:
```
Query error: Field 'PermissionID' doesn't have a default value in flush users with a qlength: 333 queue size: 2
Query error: Field 'GroupID' doesn't have a default value in flush torrents with a qlength: 273 queue size: 24
```
Any chance this error might effect tracker announces?

**Comment by Empornium** [comment]
Ah, yes. Your database is running in strict mode which we do not support. Set the sql mode to blank in your mysel config file:

```
[mysqld]
sql_mode = ""
```

**Comment by poorplanet** [comment]
That was it! Thank you for your time and your contributions to the community.
