### ISSUE TITLE
Ubuntu 16 - Error in entry.php setup install

### ISSUE THREAD

**Issue by executivoclub** [Empornium/Luminance#5]
Hello all,

I'm having this error when run "php application/entry.php setup install":

> root@ns3010422:/var/www/html# php application/entry.php setup install
PHP Warning:  Declaration of Luminance\Services\Cache::getStats($args) should be compatible with Memcached::getStats() in /var/www/html/application/Services/Cache.php on line 35
Initializing legacy database table schemas
Initializing ORM database table schemas
Initializing database contents
Please create the admin user now
Admin Username: pdh
Admin Password: *******
--- ERROR during CLI execution ---
Corresponding HTTP response status: 400
Error message: No userclasses have been configured.

I'm getting 404 error when I try to connect, maybe because the install was not sucessfull?

I'm running PHP 7.0 Ubuntu 16.04 and NGINX

**Comment by Empornium** [comment]
That's not an error, it's a warning and it's ignorable. If you want to silence it then installed the memcached plugin instead of the memcache plugin for PHP.

**Comment by executivoclub** [comment]
Im meaning this part of the error:

--- ERROR during CLI execution ---
Corresponding HTTP response status: 400
Error message: No userclasses have been configured.

**Comment by Empornium** [comment]
Your database is not empty, implying this isn't a clean install. Drop the database and re-create it.
