### ISSUE TITLE
php7.4 Installation error

### ISSUE THREAD

**Issue by baiyou2014** [Empornium/Luminance#50]
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; SphinxClient has a deprecated constructor in /www/wwwroot/t/vendor/neutron/sphinxsearch-api/sphinxapi.php on line 386

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; SphinxClient has a deprecated constructor in /www/wwwroot/t/vendor/neutron/sphinxsearch-api/sphinxapi.php on line 386
Initializing legacy database table schemas
Caught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'pt'@'localhost' (using password: YES)
#0 /www/wwwroot/t/application/Services/DB.php(122): PDO->__construct()
#1 /www/wwwroot/t/application/Services/DB.php(163): Luminance\Services\DB->connect()
#2 /www/wwwroot/t/application/Services/ORM.php(166): Luminance\Services\DB->raw_query()
#3 /www/wwwroot/t/application/Services/ORM.php(195): Luminance\Services\ORM->get_tables()
#4 /www/wwwroot/t/application/Plugins/Setup/SetupPlugin.php(138): Luminance\Services\ORM->update_tables()
#5 /www/wwwroot/t/application/Plugins/Setup/SetupPlugin.php(96): Luminance\Plugins\Setup\SetupPlugin->updateLegacyTables()
#6 [internal function]: Luminance\Plugins\Setup\SetupPlugin->install()
#7 /www/wwwroot/t/application/Core/Controller.php(38): call_user_func_array()
#8 [internal function]: Luminance\Core\Controller->handle_path()
#9 /www/wwwroot/t/application/Core/Master.php(299): call_user_func_array()
#10 [internal function]: Luminance\Core\Master->plugin()
#11 /www/wwwroot/t/application/Core/Master.php(276): call_user_func_array()
#12 /www/wwwroot/t/application/Core/Master.php(161): Luminance\Core\Master->handle_request()
#13 /www/wwwroot/t/application/entry.php(34): Luminance\Core\Master->run()
#14 {main}
PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /www/wwwroot/t/application/Services/Render.php:209
Stack trace:
#0 /www/wwwroot/t/application/Services/Render.php(522): Luminance\Services\Render->get_scripts()
#1 /www/wwwroot/t/application/Services/Render.php(159): Luminance\Services\Render->get_header_vars()
#2 /www/wwwroot/t/application/Core/Master.php(187): Luminance\Services\Render->display_page()
#3 /www/wwwroot/t/application/Core/Master.php(181): Luminance\Core\Master->process_response()
#4 /www/wwwroot/t/application/entry.php(34): Luminance\Core\Master->run()
#5 {main}
  thrown in /www/wwwroot/t/application/Services/Render.php on line 209

Fatal error: Uncaught Error: [] operator not supported for strings in /www/wwwroot/t/application/Services/Render.php:209
Stack trace:
#0 /www/wwwroot/t/application/Services/Render.php(522): Luminance\Services\Render->get_scripts()
#1 /www/wwwroot/t/application/Services/Render.php(159): Luminance\Services\Render->get_header_vars()
#2 /www/wwwroot/t/application/Core/Master.php(187): Luminance\Services\Render->display_page()
#3 /www/wwwroot/t/application/Core/Master.php(181): Luminance\Core\Master->process_response()
#4 /www/wwwroot/t/application/entry.php(34): Luminance\Core\Master->run()
#5 {main}
  thrown in /www/wwwroot/t/application/Services/Render.php on line 209

**Comment by Empornium** [comment]
PHP 7.4 is not supported by this release, it might work, it might not.

The Sphinx warning can be ignored for now. I have no idea why it's giving that error for line 209 of the Render service, and your database username/password is wrong.

**Comment by baiyou2014** [comment]
How long will the new version be released? Should I use php7.0 mysql5.7 now. Will sphinx-3.2.1 support this version? I want to upgrade my website code to Luminance. This code is great, I want to add multilingual support to him

**Comment by Empornium** [comment]
We don't have a firm date, when all the tasks for the next milestone are met we'll release it. It *SHOULD* be late summer/early fall, but I cannot guarantee that.

Sphinx-3 will not be supported in the next release and in the subsequent release sphinx support will be removed entirely.

**Comment by Empornium** [comment]
Oh, and PHP 7.1 should work with this code.

**Comment by baiyou2014** [comment]
Can I use the sphinx3 version now? I first encountered this code, it is a bit troublesome to deploy and install using centos7

**Comment by Empornium** [comment]
I honestly do not know if the API for Sphinx 3 is the same or not. Try it, it may or may not work. But the errors you are getting above are unrelated to the version of sphinx.
