### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by baiyou2014** [Empornium/Luminance#52]
Hello, I configured the access prompt 404 error under NGINX version 1.16.1.

**Comment by Empornium** [comment]
I don't understand what your issue is. Which URL gives you a 404 error?

**Comment by baiyou2014** [comment]
this is my test website. http://128.199.143.25/ 
this is nginx confg 

> server
{
    listen 80;
    listen [::]:80;
    server_name 128.199.143.25;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/t/public;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    error_page 404 /404.html;
    error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-71.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    #include /www/server/panel/vhost/rewrite/128.199.143.25.conf;
    #REWRITE-END
    location / {
  		try_files $uri /index.php?$args;
  	}


	
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log /dev/null;
    }
    
    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log off;
        access_log /dev/null; 
    }
    access_log  /www/wwwlogs/128.199.143.25.log;
    error_log  /www/wwwlogs/128.199.143.25.error.log;
}


> site_name = 'sbao'
nonssl_site_url = '128.199.143.25'
announce_url = 'http://128.199.143.25:2710'
site_url = 'http://128.199.143.25/'
mail_domain = 'http://128.199.143.25/'
static_server = '/static/'
internal_urls_regex = '@^https?:\/\/128.199.143.25\/|^https?:\/\/\/@'
non_anon_urls_regex = '@^https?:\/\/128.199.143.25|^https?:\/\/@'


It seems that the index.php file cannot be found under the public directory

**Comment by Empornium** [comment]
> It seems that the index.php file cannot be found under the public directory

That is correct, there is no index.php file, you should look at the nginx example config file included in the install directory.

https://github.com/Empornium/Luminance/blob/master/install/nginx.conf
