### ISSUE TITLE
No input file specified. 

### ISSUE THREAD

**Issue by Kufirc** [Empornium/Luminance#53]
nginx conf

```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

pid        temp/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    client_max_body_size 55m;

    #gzip  on;

	scgi_temp_path  temp/uwsgi_temp 1 2;
	uwsgi_temp_path  temp/uwsgi_temp 1 2;

	fastcgi_connect_timeout 1;


	server {
	listen 80;

       server_name testsite;

		root home/localhost/public_html;
		index index.php index.html index.htm;

		log_not_found off;
        charset utf-8;

		access_log  logs/access.log  main;


		location / {
		try_files $uri /index.php?$args;
	}

        location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass 127.0.0.1:9071;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_index index.php;

		fastcgi_buffers 16 16k; 
		fastcgi_buffer_size 32k;

		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME home/localhost/public_html/application/entry.php;
		fastcgi_keep_conn on;

        }
	}

	server {
		listen 127.0.0.1:443;
		include ssl.conf;

		root home/localhost/public_html;
		index index.php index.html;

		log_not_found off;
        charset utf-8;

		access_log  logs/access.log  main;


		location / {
		try_files $uri /index.php?$args;
	}

       location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_index index.php;

		fastcgi_buffers 16 16k; 
		fastcgi_buffer_size 32k;

		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME home/localhost/public_html/application/entry.php;
		fastcgi_keep_conn on;
	}
	}


	include tools-*.conf;

	include vhosts/*.conf;

}
```

**Comment by Empornium** [comment]
Where you have "home/" you probably want "/home/". Other than that, we don't have the resources to provide support for nginx configuration files, we provide an example which works and for all customization needs you'll need to refer to their documentation:
https://nginx.org/en/docs/

**Comment by Kufirc** [comment]
Fatal error: Uncaught Error: [] operator not supported for strings in C:\Winginx\home\public_html\application\Services\Render.php:206 Stack trace: #0 C:\Winginx\home\public_html\application\Services\Render.php(519): Luminance\Services\Render->get_scripts('') #1 C:\Winginx\home\public_html\application\Services\Render.php(159): Luminance\Services\Render->get_header_vars(Array) #2 C:\Winginx\home\public_html\application\Core\Master.php(187): Luminance\Services\Render->display_page('@Authentication...', Array, NULL) #3 C:\Winginx\home\public_html\application\Core\Master.php(162): Luminance\Core\Master->process_response(Object(Luminance\Responses\Rendered)) #4 C:\Winginx\home\public_html\application\entry.php(34): Luminance\Core\Master->run() #5 {main} thrown in C:\Winginx\home\public_html\application\Services\Render.php on line 206

Render.php on line 206:
$extra_scripts[] = 'svg-injector'; // handles icon injections

would I have missed something?

**Comment by Kufirc** [comment]
login 

Bots are forbidden

what?

**Comment by Kufirc** [comment]
where can i take it out h let me in?

**Comment by Empornium** [comment]
You need to enable javascript.

**Comment by Kufirc** [comment]
how can i contact you privately?
on monday come the new vps and i would have some issues with operating system mysql php etc etc
choosing

**Comment by Empornium** [comment]
Sorry but I don't have time to provide that level of support.
