### ISSUE TITLE
no javascript loaded

### ISSUE THREAD

**Issue by Kufirc** [Empornium/Luminance#54]
Hello
there is a problem that the show_header function does not call JavaScript just the basics

html code:

 <script src="public/static/functions/class_ajax.js?v=1553524766" type="text/javascript" integrity="sha256-IqbYAq98PS8pa0qn6i2JlYRaR1ScTCaMNuZ3LQhFqU0="></script>    
            
<script src="public/static/functions/svg-injector.js?v=1553524766" type="text/javascript" integrity="sha256-c7ta9Kl1aKLw076VEXTfyDpLojeVc7C14966LlbG1+A="></script> 
               
<script src="public/static/functions/prism.js?v=1553524766" type="text/javascript" integrity="sha256-cde8/YhFU9qDeVTAzFjXTt4Wbs0w9sWqWgJcigbYyBU="></script>  
              
<script src="public/static/functions/global.js?v=1553524766" type="text/javascript" integrity="sha256-0EKUUIc0d1O+V7Jsgru0m2IBma+QHxnx9rYmWk0rYhU="></script>   
<body id="stats">            
<div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>
            <div id="wrapper">

show_header('Site Statistics', 'charts,jquery');

charts és jquery ???

where can the problem be?

**Comment by Empornium** [comment]
The Render service handles scirpt injection.

**Comment by Kufirc** [comment]
managed was also bad the path thank you very much :)
