### ISSUE TITLE
Could you please let me register? Thank you

### ISSUE THREAD

**Issue by lotslots** [Empornium/Luminance#57]
能不能放我注册下，谢谢大神。
Could you please let me register? Thank you

**Comment by slavanomics** [comment]
Are you having an issue registering on your Luminance instance or are you just begging for an emp invite?

**Comment by lotslots** [comment]
> 您是否在亮度实例上注册了问题， 还是只是乞求 emp 邀请？

I want to enter the website, but I can't register any more. Hope to be invited.

**Comment by lotslots** [comment]
> > 您是否在亮度实例上注册了问题， 还是只是乞求 emp 邀请？
> 
> I want to enter the website, but I can't register any more. Hope to be invited.

我想进入网站，但是已经不能注册了。希望被邀请。

**Comment by Picvent** [comment]
My big brother ,please help save the rookie.Begging for an emp invite
picvent@gmail.com

**Comment by xin90n** [comment]
I want to one empornium invitation code.
444097842@qq.com
Thanks!

**Comment by xin90n** [comment]
I want an invitation from emp, thank you! 444097842@qq.com

**Comment by Arakas123** [comment]
Can someone invite me pls also on empornium
parrykashyap7@gmail.com

**Comment by pmarsden** [comment]
Seriously ?
