### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Kufirc** [Empornium/Luminance#58]
Dear empornium
I would like to know if an update to luminace and radiance is expected this year (2021)?

**Comment by Empornium** [comment]
That's a solid "maybe". We have newer code running in production but it's a non-trivial amount of effort to prepare and test it for release.

**Comment by Kufirc** [comment]
ok thank you very much for your reply

**Comment by Oha-you** [comment]
Seconding this request.. I hope more people will express their interest so we could eventually see an updated version.
Thank you, EMP ❤️

**Comment by kis2a** [comment]
yes update this please ;)

**Comment by mcangeli** [comment]
Any chance there's an updated version of the code laying around somewhere?

**Comment by Empornium** [comment]
Update released.

**Comment by Kufirc** [comment]
thank you very much, I've been waiting for it, although the older version also works perfectly thanks to you, as I can see the site has undergone a lot of development, all my respect and appreciation goes to you.
