### ISSUE TITLE
IP-related 500 Internal Server Error

### ISSUE THREAD

**Issue by kongamf** [Empornium/Luminance#62]
I am having some issues related to the various IP-tools, dupe IP checks and GeoIP updates, giving me a 500 Internal Server Error. I believe the same issue is stopping my users from downloading with the message "Invalid IP". The error log calls for an Unknown column 'bu.IP' in 'field list' which I cannot find any trace of. Everything else works fine, and uploaders are still connectable and showing as peers.

I have tried reinstalling anything I can think of, but I always end up with the same error only in various the IP tools. If relevant, I also have longstanding issues getting information from "Domain stats", but not "Tracker stats" or "DB stats".

**Comment by Empornium** [comment]
I think 0.6 which just released should resolve this issue.
