### ISSUE TITLE
Unregistered Torrent

### ISSUE THREAD

**Issue by drt420** [Empornium/Luminance#9]
Hello
I am running website and tracker on different server and everything working fine but all torrents are showing "Unregistered Torrent" while seeding or downloading.
Pls help in resolving this issue.

Regards

**Comment by Empornium** [comment]
Your Website is unable to connect to your tracker and send it updates. Restarting the tracker will cause it to reread the database and catch up but it'll only fall behind again.

Ensure you have the tracker host and port setting correctly configured in your settings.ini if they deviate from the default. For reference, the defaults are:

```
[tracker]
host=localhost
port=2710
```

Tip: use the tracker stats tool to check the site's connection to the tracker.

**Comment by drt420** [comment]
yes i tried restarting radiance and seems like it is reading db properly. I am running radiance on different server so i have changed host to that server ip address and port to 8080 as per my need but still getting same error while seeding torrent

**Comment by Empornium** [comment]
What happens when you open the tracker stats tool in your site?

**Comment by drt420** [comment]
I am getting "Failed to get tracker info" but I have no clue what went wrong.

**Comment by Empornium** [comment]
That means your configuration is wrong and the site can't contact the tracker. Double check your report keys and site keys are in sync and your host & port settings are correct.

**Comment by drt420** [comment]
I am putting reportkey in place of report_password and secret in place of site_password from settings.ini in radiance.conf. Kindly confirm if these are correct?

**Comment by drt420** [comment]
For Fedora users only, SELinux settings for httpd prohibit some outbound connections.
If it is set to off, try enabling it:
`sudo setsebool -P httpd_can_network_connect on`
